services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/src
      - /src/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true
